### ISSUE TITLE
error: [Errno 111] Connection refused No handlers could be found for logger "pyhpfeeds"

### ISSUE THREAD

**Issue by Waseem-farooqui** [threatstream/shockpot#7]
Hi,
I am setting Shockpot on Standalone Ubuntu 14.04 64-bit machine.
I just clone shockpot from repositories, `pip install -r requirements.txt` and change the port from `8080` to `80` in configurations.
Now when I start the shockpot with `sudo python shockpoy.py` it throw me this error  

    Traceback (most recent call last):
      File "/opt/shockpot/src/hpfeeds/lib/hpfeeds.py", line 137, in connect
        self.s.connect((addr, self.port))
      File "/usr/lib/python2.7/socket.py", line 224, in meth
        return getattr(self._sock,name)(*args)
    error: [Errno 111] Connection refused
    No handlers could be found for logger "pyhpfeeds"
How can I resolve it ?

**Comment by jt6211** [comment]
The error you see is from shockpot trying to connect to an hpfeeds server
that is likely not there.  If you are running standalone (i.e. not using
MHN), then you need to disable hpfeeds reporting by editing this section in
its config file.

[hpfeeds]
enabled = False
​
